version: "3.9"

services:
  jupyter:
    build:
      context: "."
      target: "development"
      args:
        USER_ID: "${USER_ID:-1000}"
        GROUP_ID: "${GROUP_ID:-1000}"
    ports:
      - "8888:8888"
    volumes:
      - ".:/usr/src/notebooks"
      - "../data:/usr/src/data"
    env_file: ".env"